### ISSUE TITLE
build guide request

### ISSUE THREAD

**Issue by dr-matt-smith** [AnTulcha/Celbridge#273]
would be nice to see a guide for building the project into an executable

**Comment by chrisgregan** [comment]
I will update the readme properly soon with some build instructions, but in the meantime here's the steps for Visual Studio on Windows.

1. Install Visual Studio (community edition is fine)
2. Setup Visual Studio for [Uno Platform development](https://platform.uno/docs/articles/get-started-vs-2022.html?tabs=ubuntu1804)
3. Open Celbridge.sln in Visual Studio

Uno Platform does some work behind the scenes when you first open the project to get everything up. It's a bit quirky. Let it idle for a minute after the solution opens, then close and reopen Visual Studio. You may need to repeat this a couple of time before it will compile and run.

Make sure you have Celbridge (WinAppSDK Packaged) and net8.0-windows10.0.22621 selected, like this:
![image](https://github.com/user-attachments/assets/dae85a42-013d-409b-aef7-6262c9e491d0)
